// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oztosavtfiifjaahpagf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dG9zYXZ0ZmlpZmphYWhwYWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDQ3MzcsImV4cCI6MjA2NTkyMDczN30.xA7EL74ACsIXCkKRoHESvKHldFjV_kjBCH6onsODHMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if we're in a secure context and configure accordingly
const isSecureContext = typeof window !== 'undefined' && window.location.protocol === 'https:';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    ...(isSecureContext && {
      // Force secure WebSocket connections in HTTPS environments
      websocket: {
        url: SUPABASE_URL.replace('https://', 'wss://') + '/realtime/v1/websocket',
      },
    }),
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web',
    },
  },
  auth: {
    persistSession: true,
  },
});